repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-docstring-first
      - id: requirements-txt-fixer
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
      - id: black
        verbose: true
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v0.0.1a2.post1
    hooks:
      - id: pyproject-flake8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
      - id: isort
        verbose: true
        additional_dependencies: [ toml ]
